name: "Build and deploy"
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: macos-10.15
    steps:
    - name: Setup | Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup | Install
      run: |
        gem install bundler
        bundle install
        carthage bootstrap
        gem install xcpretty-travis-formatter
    - name: Build
      run: |
        xcodebuild -version
        xcodebuild -target Package
    - name: Tag release
      if: "github.ref == 'refs/heads/develop'"
      run: |
        Scripts/tag-beta
      #env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
