name: "Build and deploy"
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: macos-10.15
    steps:
    - name: Setup | Checkout
      uses: actions/checkout@v2
      with:
        token: ${{secrets.SITE_TOKEN}}
        submodules: recursive
    - name: Setup | Ruby
      uses: ruby/setup-ruby@v1
    - name: Setup | Install
      run: |
        carthage bootstrap
        gem install xcpretty-travis-formatter
    - name: Build
      run: |
        xcodebuild -version
        xcodebuild -target Package
    - name: Tag release
      if: "github.ref == 'refs/heads/develop'"
      env:
          SITE_TOKEN: ${{ secrets.SITE_TOKEN }}
      run: |
        . Scripts/tag-beta.bash
